linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - decorder
    - dogsled
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - copyloopvar
    - gci
    - gocheckcompilerdirectives
    - gocognit
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - grouper
    - importas
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - rowserrcheck
    - sqlclosecheck
    - tagalign
    - tagliatelle
    - usetesting
    - testableexamples
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
    - zerologlint
    - varnamelen

linters-settings:
  gosimple:
    checks: ["all"]

  gosec:
    excludes:
      - G304
      - G204
      - G115

  stylecheck:
    checks: ["all"]

  govet:
    enable-all: true
    disable: ["fieldalignment"]

    settings:
      shadow:
        strict: true

  predeclared:
    # Comma-separated list of predeclared identifiers to not report on.
    # Default: ""
    ignore: "len, min, max"
    # Include method names and field names (i.e., qualified names) in checks.
    # Default: false
    q: true

  tagliatelle:
    # Check the struct tag name case.
    case:
      use-field-name: false
      rules:
        json: snake
        yaml: snake

  gocritic:
    disabled-checks:
      - ifElseChain
      - unnamedResult
      - importShadow
    enabled-tags:
      - diagnostic
      - style
      - performance

  nestif:
    # Minimal complexity of if statements to report.
    # Default: 5
    min-complexity: 6

  varnamelen:
    ignore-names:
      - ok
      - ip
      - no
      - tt # table tests
      - i # for simple loops
      - j # for simple loops
      - l
      - h
      - il
      - r # reader
      - w # writer

    ignore-decls:
      - wg sync.WaitGroup
      - ts *testsuite.TestSuite
      - td *testData
      - ma multiaddr.Multiaddr
      - db *leveldb.DB

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test.go
      linters:
        - maintidx
        - nestif
        - gocognit
        - forbidigo

  exclude:
    - 'shadow: declaration of "err" shadows'
    - 'builtinShadow: shadowing of predeclared identifier: min'
    - 'builtinShadow: shadowing of predeclared identifier: max'
    - 'builtinShadow: shadowing of predeclared identifier: len'
