name: Integration Tests
permissions:
  contents: read

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download Go dependencies
        run: go mod download

      - name: Run Integration Tests
        env:
          EZEX_USERS_DB_ADDRESS: localhost:5432
          EZEX_USERS_DB_DATABASE: postgres
          EZEX_USERS_DB_USERNAME: postgres
          EZEX_USERS_DB_PASSWORD: postgres
          EZEX_USERS_DB_PORT: 5432
        run: make test-integration
